Exercise 1:
Create a NumPy array of integers from 1 to 10.

In [12]:
import numpy as np
a = np.array([1,2,3,4,5,6,7,8,9,10])
print(a)

[ 1  2  3  4  5  6  7  8  9 10]



Exercise 2:
Create a 3x3 NumPy array filled with zeros.

In [15]:
import numpy as np
x = np.zeros((3,3))
print(x)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]



Exercise 3:
Create a NumPy array of 10 evenly spaced numbers between 0 and 5.



In [23]:
import numpy as np
a=np.linspace(0,5,10)
print(a)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


Exercise 4:
Create a 5x5 identity matrix using NumPy.



In [25]:
import numpy as np
c = np.eye(5,5)
print(c)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Exercise 5:
Create a 4x4 matrix with random values between 0 and 1.



In [29]:
import numpy as np
y = np.random.random([4,4])
print(y)

[[0.58063557 0.58384465 0.50534099 0.62935316]
 [0.57763641 0.87406693 0.21650879 0.23627659]
 [0.35354077 0.55359127 0.82418083 0.07251447]
 [0.50824563 0.28326854 0.27625928 0.56826186]]


Exercise 6:
Find the shape of a NumPy array.



In [34]:
import numpy as np
z = np.array([1,2,3,5,7,11])
print(z.shape)

(6,)


Exercise 7:
Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.



In [ ]:
import numpy as np
d = np.array([])

Exercise 8:
Find the data type of the elements in a NumPy array.


In [38]:
 import numpy as np
m = np.array([1,2,3,4,5], dtype=np.int32)
print(m)
n = np.array([1,2,3,4,5], dtype=np.int64)
print(n)
print(m.dtype)
print(m.nbytes)
print(n.nbytes)

[1 2 3 4 5]
[1 2 3 4 5]
int32
20
40


Exercise 9:
Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.


In [42]:
import numpy as np
q = np.arange(100)
q[q%2==0]


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

Exercise 10:
Generate a 6x6 matrix of random integers between 10 and 50.


In [52]:
import numpy as np
my_arr = np.random.randint(10,50,[6,6])
print(my_arr)




[[38 22 34 29 11 26]
 [39 10 21 40 43 34]
 [40 10 11 29 45 49]
 [13 44 37 17 12 30]
 [40 10 25 15 28 41]
 [13 36 47 34 47 11]]


Exercise 11:
Slice a 2D NumPy array to extract a submatrix.



In [63]:
import numpy as np
aaa=my_arr[1,]
print(aaa)


[39 10 21 40 43 34]


Exercise 12:
Calculate the sum of all elements in a NumPy array.

In [64]:
add = np.sum(my_arr)
print(add)

1031


In [ ]:
Exercise 13:
Calculate the mean, median, and standard deviation of a NumPy array.

In [67]:
mean = np.mean(my_arr)
print(mean)
med = np.median(my_arr)
print(med)
std = np.std(my_arr)
print(std)

28.63888888888889
29.5
12.83691027592305


Exercise 14:
Find the maximum and minimum values in a NumPy array.

In [73]:
ma = np.max(my_arr)
mi = np.min(my_arr)
print(ma)
print(mi)

49
10


In [ ]:
Exercise 15:
Create a NumPy array of 20 random integers and find the index of the maximum value.

In [84]:
t = np.random.randint(20, size= [3,3])
print(t)

[[ 1 18 10]
 [ 0 15  7]
 [14  1 19]]


In [85]:
print(np.max(t))

19


Exercise 16:
Create a NumPy array and reverse its elements.


In [90]:
import numpy as np
t = np.array([1,2,3,4])
print(np.flip(t))

[4 3 2 1]


Exercise 17:
Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.



In [91]:
import numpy as np

# Define two 3x3 matrices
matrix_a = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

matrix_b = np.array([[9, 8, 7],
                     [6, 5, 4],
                     [3, 2, 1]])

# Perform element-wise multiplication
element_wise_product = np.multiply(matrix_a, matrix_b)
print(element_wise_product)


[[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [99]:
a = np.array([[[2,3,5],[1,6,1],[4,2,1]]])
print(a)
print('--------------------------------')
b = np.array([[[2,3,5],[1,6,1],[4,2,1]]])
print(b)
print('-------------------------------')
print(np.multiply(a,b))

[[[2 3 5]
  [1 6 1]
  [4 2 1]]]
--------------------------------
[[[2 3 5]
  [1 6 1]
  [4 2 1]]]
-------------------------------
[[[ 4  9 25]
  [ 1 36  1]
  [16  4  1]]]


Exercise 18:
Create a diagonal matrix from a given 1D array.



In [100]:
f = np.array([4,5,6])
print(np.diag(f))

[[4 0 0]
 [0 5 0]
 [0 0 6]]


Exercise 19:
Perform matrix multiplication on two 2D NumPy arrays.



In [108]:
b = np.array([[1,2],[3,4]])
print(np.ndim(b))
print('----------------------------')
c = np.array([[5,6],[7,8]])
print(np.ndim(c))
print('---------------------')
print(np.matmul(b,c))

2
----------------------------
2
---------------------
[[19 22]
 [43 50]]


Exercise 20:
Flatten a 2D NumPy array into a 1D array.



In [115]:
print(np.ravel(b))

[1 2 3 4]


Exercise 21:
Stack two NumPy arrays vertically.



In [121]:
g = np.array([1,2])
h = np.array([4,5])
print(np.vstack(g))
print('---------------------------')
print(np.vstack(h))

[[1]
 [2]]
---------------------------
[[4]
 [5]]


Exercise 22:
Stack two NumPy arrays horizontally.



In [123]:
    print(np.hstack(g))
    print('-------------------------')
    print(np.hstack(h))

[1 2]
-------------------------
[4 5]


Exercise 23:
Split a NumPy array into multiple sub-arrays.

In [129]:
print(np.split(g,2))

[array([1]), array([2])]


Exercise 24:
Generate a random NumPy array and round each element to two decimal places.



In [133]:
y = np.array([2.4, 3.7])
print(np.round(y,2))

[2.4 3.7]


Exercise 25:
Find the unique elements of a NumPy array.



In [135]:
h = np.array([1,2,2,5,4,4,7])
print(np.unique(h))

[1 2 4 5 7]


Exercise 26:
Replace all elements in a NumPy array that are less than a specific value with that value.



In [137]:
m = np.array([1,2,3,4,5,6,7,8])
c = 6
m= np.where(m<c,c,m)
print(m)

[6 6 6 6 6 6 7 8]


Exercise 27:
Find the cumulative sum of the elements in a NumPy array.



In [138]:
print(np.cumsum(m))

[ 6 12 18 24 30 36 43 51]


Exercise 28:
Create a NumPy array and find the number of non-zero elements in it.



In [147]:
a = np.array([1,2,0,5,4,6,0])
print(np.count_nonzero(a))

5


Exercise 29:
Create a NumPy array of random integers and sort it in ascending order.


In [149]:
f = np.array([4,7,1,3,8,2,9,0,5])
print(np.sort(f))

[0 1 2 3 4 5 7 8 9]


Exercise 30:
Find the row-wise and column-wise sum of a 3x3 matrix.



In [153]:
d = np.array([[[1,2,3],[2,1,3],[3,2,5]]])
print(d.ndim)
rowsum = np.sum(d, axis=1)
colsum = np.sum(d, axis=0)
print(rowsum)
print(colsum)

3
[[ 6  5 11]]
[[1 2 3]
 [2 1 3]
 [3 2 5]]


Exercise 31:
Generate a 2D NumPy array with random values and normalize it (scale the values between 0 and 1).



Exercise 32:
Create two NumPy arrays and find the dot product.



In [160]:
c = np.array([1,2,3]),
b = np.array([4,5,6])
print(np.dot(c,b))

[32]


Exercise 33:
Find the trace of a square NumPy matrix.


In [162]:
n = np.array([[1,2], [3,4]])
print(n.ndim)
print(np.trace(n))

2
5


Exercise 34:
Create a 2D array and swap two rows.



In [165]:

array = np.array([[1, 2], [4,5]])
array[[0, 1]] = array[[1, 0]]
print(array)


[[4 5]
 [1 2]]


Exercise 35:
Create a 1D NumPy array and convert it into a column vector.



In [167]:

V = np.array([1, 2, 3])
column_vector = V[:, np.newaxis]
print(column_vector)


[[1]
 [2]
 [3]]


Exercise 36:
Find the determinant of a 3x3 matrix.



In [170]:
d = np.array([[[1,2,3],[2,3,3],[2,5,4]]])
print(np.linalg.det(d))

[5.]


In [ ]:
Exercise 37:
Find the eigenvalues and eigenvectors of a 2x2 matrix.

# Exercise 37
Exercise 38:
Solve a system of linear equations using NumPy.

# Exercise 38
Exercise 39:
Add Gaussian noise to a NumPy array.

# Exercise 39
Exercise 40:
Create a 4x4 matrix and extract the diagonal elements.

# Exercise 40
Exercise 41:
Generate a NumPy array of 100 random values and clip the values to a range between 10 and 50.

# Exercise 41
Exercise 42:
Create a 2D NumPy array and replace all negative values with zero.

# Exercise 42
Exercise 43:
Find the inner and outer products of two NumPy arrays.

# Exercise 43
Exercise 44:
Calculate the pairwise distances between points in a NumPy array.

# Exercise 44
Exercise 45:
Create a structured NumPy array with fields for name, age, and height.

# Exercise 45
Exercise 46:
Create a 5x5 matrix of random integers and count the occurrences of each unique value.

# Exercise 46
Exercise 47:
Generate a random 3x3 NumPy array and subtract the mean of each row from the corresponding row.

# Exercise 47
Exercise 48:
Create a NumPy array of random integers and check if any of the values are greater than 50.

# Exercise 48
Exercise 49:
Calculate the moving average of a 1D NumPy array.

# Exercise 49
Exercise 50:
Find the Pearson correlation coefficient between two NumPy arrays.

# Exercise 50
Exercise 51:
Convert a NumPy array of radians to degrees.

# Exercise 51
Exercise 52:
Create a random NumPy array and compute its variance and standard deviation.

# Exercise 52
Exercise 53:
Create a 2D NumPy array and find the indices of the maximum values along each axis.

# Exercise 53
Exercise 54:
Compute the inverse of a 2x2 NumPy matrix.

# Exercise 54
Exercise 55:
Create a NumPy array of 10 random values and standardize it (mean 0, variance 1).

# Exercise 55
Exercise 56:
Perform element-wise addition and subtraction on two NumPy arrays.

# Exercise 56
Exercise 57:
Create a NumPy array of random values and find the maximum element’s index.

# Exercise 57
Exercise 58:
Create a 3x3 NumPy array and rotate it by 90 degrees.

# Exercise 58
Exercise 59:
Compute the Frobenius norm of a matrix.

# Exercise 59
Exercise 60:
Create a 3D NumPy array and slice out a subarray.

# Exercise 60